/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopas

import (
	"encoding/json"
)

// PlatformListModel struct for PlatformListModel
type PlatformListModel struct {
	Platforms *[]PlatformModel `json:"Platforms,omitempty"`
	Total     *float32         `json:"Total,omitempty"`
}

// NewPlatformListModel instantiates a new PlatformListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformListModel() *PlatformListModel {
	this := PlatformListModel{}
	return &this
}

// NewPlatformListModelWithDefaults instantiates a new PlatformListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformListModelWithDefaults() *PlatformListModel {
	this := PlatformListModel{}
	return &this
}

// GetPlatforms returns the Platforms field value if set, zero value otherwise.
func (o *PlatformListModel) GetPlatforms() []PlatformModel {
	if o == nil || o.Platforms == nil {
		var ret []PlatformModel
		return ret
	}
	return *o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformListModel) GetPlatformsOk() (*[]PlatformModel, bool) {
	if o == nil || o.Platforms == nil {
		return nil, false
	}
	return o.Platforms, true
}

// HasPlatforms returns a boolean if a field has been set.
func (o *PlatformListModel) HasPlatforms() bool {
	if o != nil && o.Platforms != nil {
		return true
	}

	return false
}

// SetPlatforms gets a reference to the given []PlatformModel and assigns it to the Platforms field.
func (o *PlatformListModel) SetPlatforms(v []PlatformModel) {
	o.Platforms = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PlatformListModel) GetTotal() float32 {
	if o == nil || o.Total == nil {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformListModel) GetTotalOk() (*float32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PlatformListModel) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *PlatformListModel) SetTotal(v float32) {
	o.Total = &v
}

func (o PlatformListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Platforms != nil {
		toSerialize["Platforms"] = o.Platforms
	}
	if o.Total != nil {
		toSerialize["Total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformListModel struct {
	value *PlatformListModel
	isSet bool
}

func (v NullablePlatformListModel) Get() *PlatformListModel {
	return v.value
}

func (v *NullablePlatformListModel) Set(val *PlatformListModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformListModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformListModel(val *PlatformListModel) *NullablePlatformListModel {
	return &NullablePlatformListModel{value: val, isSet: true}
}

func (v NullablePlatformListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
