/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopas

import (
	"encoding/json"
)

// A2j struct for A2j
type A2j struct {
	PSMConnectorID string `json:"PSMConnectorID"`
	Enabled        bool   `json:"Enabled"`
}

// NewA2j instantiates a new A2j object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewA2j(pSMConnectorID string, enabled bool) *A2j {
	this := A2j{}
	this.PSMConnectorID = pSMConnectorID
	this.Enabled = enabled
	return &this
}

// NewA2jWithDefaults instantiates a new A2j object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewA2jWithDefaults() *A2j {
	this := A2j{}
	return &this
}

// GetPSMConnectorID returns the PSMConnectorID field value
func (o *A2j) GetPSMConnectorID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PSMConnectorID
}

// GetPSMConnectorIDOk returns a tuple with the PSMConnectorID field value
// and a boolean to check if the value has been set.
func (o *A2j) GetPSMConnectorIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PSMConnectorID, true
}

// SetPSMConnectorID sets field value
func (o *A2j) SetPSMConnectorID(v string) {
	o.PSMConnectorID = v
}

// GetEnabled returns the Enabled field value
func (o *A2j) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *A2j) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *A2j) SetEnabled(v bool) {
	o.Enabled = v
}

func (o A2j) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["PSMConnectorID"] = o.PSMConnectorID
	}
	if true {
		toSerialize["Enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableA2j struct {
	value *A2j
	isSet bool
}

func (v NullableA2j) Get() *A2j {
	return v.value
}

func (v *NullableA2j) Set(val *A2j) {
	v.value = val
	v.isSet = true
}

func (v NullableA2j) IsSet() bool {
	return v.isSet
}

func (v *NullableA2j) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableA2j(val *A2j) *NullableA2j {
	return &NullableA2j{value: val, isSet: true}
}

func (v NullableA2j) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableA2j) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
